name = "AdamVig"
license = "MIT"
licenselink = "https://github.com/AdamVig/blog/blob/main/themes/adamvig/LICENSE"
description = "Theme for blog.adamvig.com"
homepage = "https://github.com/AdamVig/blog"
tags = []
features = []
min_version = "0.80.0"

[author]
  name = "Adam Vigneaux"
  homepage = "https://adamvig.com"
